print(" ========== tabuada ===========")
a = int(input(print("insert a number ")))
print(12 * '=')
print('1 X {:2} = '.format(a), a * 1)
print('2 X {:2} = '.format(a), a * 2)
print('3 X {:2} = '.format(a), a * 3)
print('4 X {:2} = '.format(a), a * 4)
print('5 X {:2} = '.format(a), a * 5)
print('6 X {:2} = '.format(a), a * 6)
print('7 X {:2} = '.format(a), a * 7)
print('8 X {:2} = '.format(a), a * 8)
print('9 X {:2} = '.format(a), a * 9)
print('{:2} X {:2} = '.format(10, a), a * 10)
print(12 * '=')